### ISSUE TITLE
Question about generate contribution score bigwigs

### ISSUE THREAD

**Issue by zhenzuo2** [kundajelab/chrombpnet#100]
Hi,

Thank you for developing this tool. I am not sure what are the forward and reserve means in the contribution score bigwigs. Are contribution score computed by forward and reserve track separately? Thanks!

**Comment by panushri25** [comment]
Hello @zhenzuo2 

Do you mean forward and reserve in the modisco output? Can you give more details?

Thank you,
Anu

**Comment by zhenzuo2** [comment]
![image](https://user-images.githubusercontent.com/13971930/233253586-9ee38cc3-fa37-4706-bf9b-decee37a4872.png)
Hi Anu,

Sure. Here is an example showing the `.counts_scores.bw` from `chrombpnet contribs_bw` in WashU Epigenome browser. The bottom orange ones are for the reserve strand. 

Best,

Zhen

**Comment by panushri25** [comment]
Do you have a corresponding modisco for this?

Also when using contribution scores in Washu use the dynseq option instead of the bigwigs. After this if you zoom onto a location you will see the motifs.

The negative contribution scores are showing up in yellow. For example in this screen shot the ZBT7A (highlighted in green) motif shows up as yellow in the bigwig tracks. It is repressing accessibility at this locus. 

<img width="688" alt="image" src="https://user-images.githubusercontent.com/13175299/233258833-f8b029ba-99d9-44ba-aa4a-33cc89d8c7cb.png">

**Comment by panushri25** [comment]
I am closing this thread because of inactivity. Feel free to open it if unresolved.
