### ISSUE TITLE
Question on validation and dara preprocessing

### ISSUE THREAD

**Issue by zixiaowang17** [kundajelab/chrombpnet#135]
Hi- 

Thank you so much for this excellent work and well-established package!

I have some minor questions here:

-	Validation. While I was running the pipeline, I was wondering how to verify my result w/ yours. Do you have any suggestions for validation, like the output file/output result; besides how can we set random seed in ChromBPNet for the sake of reproducibility? 
-	Data preprocessing: I also noticed that it takes quite a while for preprocessing in chrombpnet pipeline to output:
Estimating enzyme shift in input file
Current estimated shift: +0/+0
Making BedGraph
Making Bigwig
Therefore I was wondering, whether I could generate the data separately from chrombpnet pipeline and possibly use the processed data as input for the training stage.

Best,
Zixiao

**Comment by panushri25** [comment]
Hello @ZixiaoWang17 

Thank you for your encouraging words! 

You can set the seed with `-s` which is default to 1234. In general Tensorflow (package used here for training) ensures  reproducibility (of the learnt weights) only if the models are trained on a CPU. GPU runs are usually not reproducible across different GPUs ([here](https://saturncloud.io/blog/tensorflow-different-results-on-different-gpus/) is blog which summarizes this). But that said you can expect similar output performance across different runs. 

The best way to make sure everything is set up properly is to run the tutorial and compare the output reports with that provided. 

We currently do not have a pipeline that separates these 2 stages. This is because the shifts used in generating the bigwigs are extremely essential for correct model training and bias correction. We are trying to figure out a way to make these stages independent while ensuring reliability.

**Comment by ArnovanHilten** [comment]
Hi Anushri,

I'm also quite interested in the same topic, I am in a similar situation. Can you expand a bit on why this shift is extremely essential? I have looked into the code but I did not get a clear picture of all the preprocessing steps.

In Zuxiao's example:

> Estimating enzyme shift in input file
> Current estimated shift: +0/+0
> Making BedGraph
> Making Bigwig

In this case, there is no shift applied right? And say that this would be one cell-type, can I than safely assume that there would be no shift in another cell-type (data from the same batch)? Are there any other preprocessing steps applied or could I use the existing BigWig files that I have. I am fairly new to this field so I am a bit anxious to miss an important step.

I already have my data in both BAMs and BigWig format. I was hoping to convert one or two Bams again to BigWig and see if there is a shift detected, and otherwise use the BigWig files I already converted before.

Best,

Arno

**Comment by panushri25** [comment]
The code is first estimating if there is an existing shift in your bams (input bams can have no shift or sometimes a +4/-5 shift both of which are incorrect). Currently the prompt is saying that there is no shift in your bams. And hence it will go ahead and make a shift of +4 on the positive strand and -4 on the negative strand. 

The package does not allow the use of existing bigwigs and will take care of all the preprocessing steps -  in terms of bam shifting and making bigwigs. For other preprocessing steps such as filtering etc - I recommend you go over the  https://github.com/kundajelab/chrombpnet/wiki/Preprocessing page here. 


Here is a quick documentation on why the shifts are important - https://github.com/kundajelab/chrombpnet/tree/master/chrombpnet/helpers/preprocessing

**Comment by panushri25** [comment]
Here are the 2 lines which convert the input bams to bigwigs  after making appropriate shift on the bams

https://github.com/kundajelab/chrombpnet/blob/d3684388512ad2248ac1c2d1dfd36167b634e816/chrombpnet/helpers/preprocessing/reads_to_bigwig.py#L40

https://github.com/kundajelab/chrombpnet/blob/d3684388512ad2248ac1c2d1dfd36167b634e816/chrombpnet/helpers/preprocessing/reads_to_bigwig.py#L46
