### ISSUE TITLE
contribs_bw slow?

### ISSUE THREAD

**Issue by YichaoOU** [kundajelab/chrombpnet#166]
Hello,

If I want to make a whole genome prediction, it seems the program is very slow?

Following the `Wiki` instruction, I created the bed10 file:

```
bedtools makewindows -g hg19_main.chrom_sizes -w 1000 -s 750 | awk -v OFS="\t" '($3-$2)/2 ==500 {print $1,$2,$3,".",".",".",".",".",".",($3-$2)/2}' > hg19_main.chrombpnet.bed10
```

There are ~4M lines.

```
chrombpnet contribs_bw -m $jid/chrombpnet_model2/models/chrombpnet_nobias.h5 -r chr1.chrombpnet.bed10 -g hg19.main.rmM.fa -c hg19.main.size -op $jid/contribs_bw/contribs

```

I only did it for `chr1`, which contains 330K lines, and it took ~10 hours.

Is this speed normal? 

Thanks,
Yichao

**Comment by panushri25** [comment]
Yes contribs takes a while, because for every region we are also generating contribs for 20 other reference regions and considering their difference from reference. This is more to do with deeplift/deepshap function. 

Also use the latest version for contribs, as it filters out edge regions and you dont have to worry about it
