### ISSUE TITLE
Plugging peak calls from ArchR

### ISSUE THREAD

**Issue by Brawni** [kundajelab/chrombpnet#209]
Dear chrombpnet devs,

Thanks for this package I'm very excited to trying it out! I'm working on scatac-seq and wondering whether I could input the peaks called from ArchR to the model or I should recall them? Through ArchR MACS2 callpeaks function is specified with an offset of -75 bp and extsize of 150bp. Is this ok?

**Comment by panushri25** [comment]
You can follow the peak-calling outlined in ENCODE ATAC-seq protocol  (Section 3a)

https://docs.google.com/document/d/1f0Cm4vRyDQDu0bMehHD7P7KOMxTOP-HiNoIvL1VcBt8/edit?tab=t.0

Posting pseudo code for this

```
pval_thresh=0.01
NPEAKS=200000 # capping number of peaks called from MACS2
smooth_window=150 # default
shiftsize=$(( -$smooth_window/2 ))

macs2 callpeak \
    -t $tag -f BAM -n $prefix -g $gensz -p $pval_thresh \
   --shift $shiftsize  --extsize $smooth_window --nomodel --keep-dup all --call-summits
```

**Comment by 09oulin** [comment]
@panushri25 Hello,

Because of the large memory the bam files need, and I plan to train a lot of models for each cell type using our scatac-seq data, I want to use the fragment file as input instead of bam file, may I change -f BAM into -f BED or -f BEDPE? Could you please give me some advice on it? I recently found these two options produce different results. 

Thanks for your time!

Lin Ou
