### ISSUE TITLE
Seqlet positions with relation to bed's

### ISSUE THREAD

**Issue by jeffsteimle** [kundajelab/chrombpnet#97]
I was hoping to pull the exact positions of the seqlets in the genome, but I am having trouble understanding the positioning information provided for each seqlet.

I pulled from the modisco output (./chrombpnet_model/auxiliary/interpret_subsample/modisco_results_profile_scores.h5) the pattern of interest and the example_idx's, start's and end's. I next matched them up with the indexed bed file (./chrombpnet_model/auxiliary/interpret_subsample/chrombpnet_nobias.interpreted_regions.bed). 

For example, the first seqlet of interest corresponds to:
idx: 18143
start: 323
end: 353

The narrowPeak corresponds to:
18143 chr9 96382967 96384261 peak_1234 84  . 3.75264 11.62406 8.4626 18144 803

I also pulled the seqlet sequence and I know that it appears at:
chr9:96383844-96383874

I assumed that the modisco h5 start/end would correspond to relative position within the peak, but that doesn't line up or else the seqlet would be at chr9:96383290-96383320

Is there something I am missing? For example, are all peaks narrowed down to a specific length around the summit or something?

Any help would be greatly appreciated!
Jeff

**Comment by panushri25** [comment]
Hello,

What do you mean by `you pulled the seqlet sequence` ?

So the peak is first centered at the summit - so this gives the center 96382967+ 803

Then modisco-lite default crops it 500 length sequence around the summit so the start of the sequence for modisco is at - 96382967+ 803 - 250 

Since the start of the seqlet is at 323, I would expect the start to be at 96382967+ 803 - 250 + 323 (963838443)

**Comment by panushri25** [comment]
Thanks for the question, I think I will include this in the documentation

**Comment by jeffsteimle** [comment]
> What do you mean by `you pulled the seqlet sequence` ?

In the h5, /pos_patterns/pattern_0/seqlets/sequence, you provide the seqlet sequence, which I converted to letters and found that in the genome. 

> Then modisco-lite default crops it 500 length sequence around the summit so the start of the sequence for modisco is at - 96382967+ 803 - 250
> 
> Since the start of the seqlet is at 323, I would expect the start to be at 96382967+ 803 - 250 + 323 (963838443)

Oh perfect! I was starting to assume it was doing some sort of crop, but I wanted to confirm. This solves my issue, thank you.

Jeff

**Comment by panushri25** [comment]
Hello folks,

Here is the official tool from the lab to identify seqlets - https://github.com/austintwang/finemo_gpu

**Comment by XuanrZhang** [comment]
Hello @panushri25 ,

Thank you for developing this useful tool. I have a follow-up question regarding its use. I ran MoDISco motifs and attempted to extract the pattern sequences from the genome. Unfortunately, I encountered the same issue as before, but this time I used MoDISco instead of MoDISco-lite. Could you inform me what the default chop length for MoDISco is? I tried using 500, but the sequences didn’t align correctly.


> Hello,
> 
> What do you mean by `you pulled the seqlet sequence` ?
> 
> So the peak is first centered at the summit - so this gives the center 96382967+ 803
> 
> Then modisco-lite default crops it 500 length sequence around the summit so the start of the sequence for modisco is at - 96382967+ 803 - 250
> 
> Since the start of the seqlet is at 323, I would expect the start to be at 96382967+ 803 - 250 + 323 (963838443)
